# Generated by Django 3.2.7 on 2021-10-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtefactClass',
            fields=[
                ('class_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('schema_definition', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_data', models.JSONField()),
                ('artefact_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artefactclass')),
            ],
        ),
    ]
