# Generated by Django 3.2.7 on 2022-04-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactType',
            fields=[
                ('schema', models.JSONField()),
                ('type_name', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=120)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.artefact')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.artefact')),
            ],
        ),
        migrations.AddField(
            model_name='artefact',
            name='artefact_type_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='api.artefacttype'),
        ),
    ]
