# version 0.1
jeyn build --all

jeyn build train

jeyn version train --major

jeyn run dataset --version==2.3.1

jeyn schedule train --version==2.5.2 --cron="*/ */ 1"

# version 0.3 (cookie-cutter)
jeyn new_project demo_project
jeyn operation train_model --description="the operation tha trains the molde"
jeyn operation build_dataset --description="the oeperation that gets new batches of dataset"

