apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jeynComponents.workflowController.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.jeynComponents.workflowController.name }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ .Values.jeynComponents.workflowController.port }}
      targetPort: {{ .Values.jeynComponents.workflowController.port }}
