apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "test-job"
    spec:
      containers:
      - name: testjob
        image: test-script
        imagePullPolicy: Never
      restartPolicy: Never