# Default values for jeyn_core_charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
daprComponents:
  redis:
    port: 6379
jeynComponents:
  artefactStore:
    name: artefact-store
    replicas: 1
    port: 8000
    image: artefactstore
    daprId: artefact-store
  workflowController:
    name: workflow-controller
    replicas: 1
    port: 8000
    daprId: workflow-controller
    image: workflowcontroller

